import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@components/Navbar";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#f9fafb", // Tailwind's gray-50
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="bg-gray-50">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 bg-gray-50 text-gray-900`}
      >
        {/* Full-viewport background */}
        <main className="w-full min-h-screen bg-gray-50">
          {/* Navbar at the top */}
          <Navbar />

          {/* Centered content container */}
          <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 lg:px-16 xl:px-24">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}